application: secondhomebeta
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /css
  static_dir: css

- url: /img
  static_dir: img

- url: /js
  static_dir: js

# fonts
- url: /fonts
  static_dir: fonts
  
# lib
- url: /lib
  static_dir: lib

# Handler for front page
- url: /
  script: secondhome.app
   
 
# All other pages require login
- url: /.*
  script: secondhome.app
  login: required
 
libraries:
- name: jinja2
  version: latest